### ISSUE TITLE
synchronizer.properties file is required, contrary to docs

### ISSUE THREAD

**Issue by onstottj** [literalice/gradle-aws-s3-sync#10]
Hi,

First, thanks for the great product!

I noticed that if I don't specify a synchronizer.properties file of some sort, I get an error message:

> Neither path nor baseDir may be null or empty string. path='null' basedir='C:\MyProjectPath'

The documentation could be updated to say that a blank file could be specified, or just update the code so that a config file isn't required. 

Thanks!

**Comment by literalice** [comment]
Thank you for reporting the issue.
I've fixed it to be able to use the task without specifying `configFile`.
