### ISSUE TITLE
Setting custom MIME type

### ISSUE THREAD

**Issue by BrandonSmith** [literalice/gradle-aws-s3-sync#11]
It isn't clear to me how I can set a custom mime type. In particular, I am uploading Android .apk files to S3 and need to set the MIME type for the Content-Type header to application/vnd.android.package-archive. How can this be achieved with gradle-aws-s3-sync?

I could fork the repo and edit gradle-aws-s3-sync/src/main/resources/mime.types, but I'm wondering if there is a better way.

**Comment by rkistner** [comment]
I have exactly the same issue. Would be great if we could specify the path to the mime.types file.
