### ISSUE TITLE
task ':deploy'. error

### ISSUE THREAD

**Issue by Espigah** [literalice/gradle-aws-s3-sync#12]
Execution failed for task ':deploy'.
> No such property: dest for class: com.monochromeroad.gradle.plugin.aws.s3.S3Sync_Decorated
Possible solutions: ant

```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath "com.monochromeroad.gradle-plugins:gradle-aws-s3-sync:0.5"
    }
}

import com.monochromeroad.gradle.plugin.aws.s3.S3Sync
ext {
    aws = [accessKey: 'XXX', secretKey: 'XXX']
}

task deploy(type: S3Sync){
    description = "Downloads files from s3 bucket to a local directory"

    configFile "synchronizer.properties"
    acl com.monochromeroad.gradle.plugin.aws.s3.ACL.PublicRead
    // follows the jets3t conventions for action names
    action = 'DOWN'

    from "XXX"
    into "YYY"
}
```

**Comment by Espigah** [comment]
your example works fine

https://github.com/literalice/gradle-aws-s3-sync/blob/master/sample/build.gradle

**Comment by literalice** [comment]
Thank you for reporting some issues.
I'll investigate them.

**Comment by statik** [comment]
I'm hitting this same error, any tips on how to work around it?

**Comment by statik** [comment]
Turns out the problem was already fixed, I just needed to be sure I was pulling in version 0.8 of the plugin instead of version 0.7.

**Comment by literalice** [comment]
@statik Thank you for your information. I've closed the issue.
